version: '3'
services:
  laravel-franken:
    container_name: laravel-franken-php
    image: laravel-franken-php
    build:
      context: .
      dockerfile: worker.dockerfile
    ports:
      - "8001:8000"
    env_file:
      - .env
